"""Thymira contracts — Contract v0.9 (see docs/contracts/contract-v0.1.md).

Typed, immutable records shared by every component: Run, Session, Agent, Task, ToolCall,
Artifact, Experiment, Event, AuditFinding, PolicyDecision, ProjectConfig, and the closed
vocabularies they use. Nothing here imports from the runtime, the API or the adapters.
"""

from thymira.schemas.actor import Actor
from thymira.schemas.agent import Agent, Task
from thymira.schemas.artifact import Artifact
from thymira.schemas.audit import AuditFinding, Evidence
from thymira.schemas.authorization import (
    DECISION_ID_KEYS,
    ActionIntent,
    ActionKind,
    Approval,
    AuthorizationContext,
    approval_decision_id,
    approval_names_decision,
)
from thymira.schemas.base import ThymiraModel, utc_now
from thymira.schemas.board import (
    BoardSnapshot,
    DagBoard,
    DagNode,
    GoalRevision,
    GoalRound,
    GoalStatus,
    PlanArtifactRef,
    PlanBoard,
    PlanFeedbackResult,
    PlanMode,
    PlanReviewDecision,
    PlanReviewPayload,
    TodoCompletion,
    TodoItem,
    TodoState,
    ToolRepeatState,
)
from thymira.schemas.credentials import is_credential_environment_name
from thymira.schemas.enums import (
    RUN_TRANSITIONS,
    ActorKind,
    ArtifactKind,
    AuditDisposition,
    AuthorizationDecision,
    Decision,
    EventSurface,
    EventType,
    ExperimentStatus,
    Framework,
    Layer,
    ReasoningStatus,
    ResponseOutcome,
    RunStatus,
    SandboxEnforcement,
    SandboxMode,
    Severity,
    StopReason,
    SurfaceState,
    TaskStatus,
    ToolCallStatus,
    can_transition,
)
from thymira.schemas.event import EVENT_LOG_FORMAT_VERSION, GENESIS_HASH, Event
from thymira.schemas.execution import ExecutionAction, ExecutionConstraints
from thymira.schemas.experiment import Experiment
from thymira.schemas.ids import Id, IdKind, id_kind, new_id
from thymira.schemas.lifecycle import (
    AuditOutcome,
    AuditOutcomeKind,
    AuthorityProof,
    ControlInput,
    ControlInputKind,
    ControlInputState,
    DispatchState,
    EnqueueReceipt,
    ExecutionOutcome,
    ExecutionOutcomeKind,
    FailureCause,
    InboxLane,
    JsonObject,
    JsonValue,
    OutboxNotification,
    OwnerReleaseReason,
    PreparedPublication,
    PublicationReceipt,
    RunOwnerHandle,
    TerminalAuditBinding,
    TerminalBinding,
    TurnEnded,
    TurnEndReason,
    TurnRecord,
    WorkClaim,
    WorkItem,
    WorkNotification,
    WorkResult,
    WorkState,
)
from thymira.schemas.mira import (
    ActivityProfile,
    ControlEvaluation,
    ControlEvaluationStatus,
    DecisionContext,
    DecisionContextStatement,
    PackBinding,
)
from thymira.schemas.model_routes import ALLOWED_MODEL_ROUTES_ENV_VAR, ModelRoutePolicy
from thymira.schemas.policy import PolicyDecision
from thymira.schemas.project import (
    AgentsConfig,
    DatasetConfig,
    ExperimentsConfig,
    GovernanceConfig,
    ProjectConfig,
    ProjectInfo,
)
from thymira.schemas.request_ledger import (
    REQUEST_LEDGER_VERSION,
    RESPONSE_LEDGER_VERSION,
    ProviderGatewayRequest,
    ProviderMessage,
    ProviderRequest,
    ProviderToolCall,
    ProviderToolDefinition,
    ReasoningMetadata,
    RequestFactOwner,
    RequestHeader,
    ResponseChunk,
    ResponseTerminal,
    RuntimeSkillRequestBinding,
    SurfaceOperation,
)
from thymira.schemas.risk import RiskAssessment, RiskLevel
from thymira.schemas.run import Run, Session
from thymira.schemas.run_state import (
    CompositeRunState,
    RunCondition,
    RunOutcome,
    RunStage,
    RunState,
    WaitReason,
)
from thymira.schemas.settings import SecretReference, SettingsSnapshot
from thymira.schemas.subagent import DELEGATION_KEY_PATTERN, SubagentResult
from thymira.schemas.tool_call import ToolCall
from thymira.schemas.tool_refusals import (
    AGENT_ALLOWLIST_REFUSAL,
    FS_AMBIGUOUS_MATCH,
    FS_NO_MATCH,
    FS_READ_REQUIRED,
    FS_STALE_VERSION,
    HUMAN_REVIEW_REFUSAL,
    MISSING_EVIDENCE_REFUSAL,
    TOOL_CALL_LIMIT_REFUSAL,
    agent_allowlist_refusal,
    ambiguous_match_refusal,
    constraint_refusals,
    no_match_refusal,
    read_required_refusal,
    stale_version_refusal,
)
from thymira.schemas.workspace import WorkspaceRegistration

CONTRACT_VERSION = "0.9"

__all__ = [
    "AGENT_ALLOWLIST_REFUSAL",
    "ALLOWED_MODEL_ROUTES_ENV_VAR",
    "CONTRACT_VERSION",
    "DECISION_ID_KEYS",
    "DELEGATION_KEY_PATTERN",
    "EVENT_LOG_FORMAT_VERSION",
    "FS_AMBIGUOUS_MATCH",
    "FS_NO_MATCH",
    "FS_READ_REQUIRED",
    "FS_STALE_VERSION",
    "GENESIS_HASH",
    "HUMAN_REVIEW_REFUSAL",
    "MISSING_EVIDENCE_REFUSAL",
    "REQUEST_LEDGER_VERSION",
    "RESPONSE_LEDGER_VERSION",
    "RUN_TRANSITIONS",
    "TOOL_CALL_LIMIT_REFUSAL",
    "ActionIntent",
    "ActionKind",
    "ActivityProfile",
    "Actor",
    "ActorKind",
    "Agent",
    "AgentsConfig",
    "Approval",
    "Artifact",
    "ArtifactKind",
    "AuditDisposition",
    "AuditFinding",
    "AuditOutcome",
    "AuditOutcomeKind",
    "AuthorityProof",
    "AuthorizationContext",
    "AuthorizationDecision",
    "BoardSnapshot",
    "CompositeRunState",
    "ControlEvaluation",
    "ControlEvaluationStatus",
    "ControlInput",
    "ControlInputKind",
    "ControlInputState",
    "DagBoard",
    "DagNode",
    "DatasetConfig",
    "Decision",
    "DecisionContext",
    "DecisionContextStatement",
    "DispatchState",
    "EnqueueReceipt",
    "Event",
    "EventSurface",
    "EventType",
    "Evidence",
    "ExecutionAction",
    "ExecutionConstraints",
    "ExecutionOutcome",
    "ExecutionOutcomeKind",
    "Experiment",
    "ExperimentStatus",
    "ExperimentsConfig",
    "FailureCause",
    "Framework",
    "GoalCreatePayload",
    "GoalEditPayload",
    "GoalRevision",
    "GoalRound",
    "GoalStatus",
    "GovernanceConfig",
    "Id",
    "IdKind",
    "InboxLane",
    "JsonObject",
    "JsonValue",
    "Layer",
    "ModelRoutePolicy",
    "OutboxNotification",
    "OwnerReleaseReason",
    "PackBinding",
    "PlanArtifactRef",
    "PlanBoard",
    "PlanFeedbackResult",
    "PlanMode",
    "PlanReviewDecision",
    "PlanReviewPayload",
    "PolicyDecision",
    "PreparedPublication",
    "ProjectConfig",
    "ProjectInfo",
    "ProviderGatewayRequest",
    "ProviderMessage",
    "ProviderRequest",
    "ProviderToolCall",
    "ProviderToolDefinition",
    "PublicationReceipt",
    "ReasoningMetadata",
    "ReasoningStatus",
    "RequestFactOwner",
    "RequestHeader",
    "ResponseChunk",
    "ResponseOutcome",
    "ResponseTerminal",
    "RiskAssessment",
    "RiskLevel",
    "Run",
    "RunCondition",
    "RunOutcome",
    "RunOwnerHandle",
    "RunStage",
    "RunState",
    "RunStatus",
    "RuntimeSkillRequestBinding",
    "SandboxEnforcement",
    "SandboxMode",
    "SecretReference",
    "Session",
    "SettingsSnapshot",
    "Severity",
    "StopReason",
    "SubagentResult",
    "SurfaceOperation",
    "SurfaceState",
    "Task",
    "TaskStatus",
    "TerminalAuditBinding",
    "TerminalBinding",
    "ThymiraModel",
    "TodoCompletion",
    "TodoItem",
    "TodoState",
    "ToolCall",
    "ToolCallStatus",
    "ToolRepeatState",
    "TurnEndReason",
    "TurnEnded",
    "TurnRecord",
    "WaitReason",
    "WorkClaim",
    "WorkItem",
    "WorkNotification",
    "WorkResult",
    "WorkState",
    "WorkspaceRegistration",
    "agent_allowlist_refusal",
    "ambiguous_match_refusal",
    "approval_decision_id",
    "approval_names_decision",
    "can_transition",
    "constraint_refusals",
    "id_kind",
    "is_credential_environment_name",
    "new_id",
    "no_match_refusal",
    "read_required_refusal",
    "stale_version_refusal",
    "utc_now",
]
