"""Thymira Runtime core: run services, LangGraph wiring and lifecycle boundaries.

Owner (MVP roadmap): P1. Today: provenance capture, the phase machine, repository-backed
Run/Session services and the initial runtime-to-LangGraph state (Contract 0.2 flat status), plus
the Contract 0.3 composite run-state machine and the ``MiraControlPlane``/``RunController``
control plane that authorizes and persists transitions through the Policy Engine and the Gate;
composition and advanced resume controls follow (ADR-0002 appendix A, ADR-0008, ADR-0010).
"""

from thymira.core.audit_freshness import AuditFreshnessAssessment, AuditFreshnessService
from thymira.core.control_plane import (
    AuthorizationError,
    AuthorizationScopeError,
    ControlPlaneResult,
    ExpiredAuthorizationError,
    MiraControlPlane,
    ReusedAuthorizationError,
    RunController,
    RunEventLog,
)
from thymira.core.decisions import (
    AnalyticalAnswer,
    AutomaticResolver,
    DecisionMode,
    DecisionRequest,
    DecisionResolution,
    DecisionResolver,
    HumanConfirmResolver,
    LlmProposesHumanConfirmsResolver,
)
from thymira.core.dispatch import (
    ExecutionDispatcher,
    ExecutionDispatchError,
    GraphFactory,
    InlineDispatcher,
)
from thymira.core.goal_board import (
    AutonomousRoundLimitError,
    GoalAuthorityError,
    GoalBoardConfig,
    GoalBoardError,
    GoalBoardService,
    GoalRevisionConflictError,
    PlanReviewRequiredError,
    RepeatBlockedError,
    RepeatDecision,
)
from thymira.core.graph import (
    MiraSubgraph,
    RunGraphState,
    RuntimeState,
    StateCheckpointer,
    Subgraph,
    SubgraphDeps,
    ThyExecutionError,
    ThySubgraph,
    build_audit_agent_runner,
    build_risk_interview_model_context,
    build_runtime_graph,
    build_runtime_graph_factory,
    composed_graph_definition_hash,
    default_activity_profile,
    default_thy_catalog,
    deserialize_runtime_state,
    graph_definition_hash,
    initial_graph_state,
    initial_runtime_state,
    serialize_runtime_state,
    write_run_assurance,
)
from thymira.core.idempotency import (
    DuplicateExecutionError,
    IdempotencyJournal,
    compute_execution_key,
)
from thymira.core.lifecycle_adapter import (
    LifecycleGraphExecutor,
    LifecycleNotificationConsumer,
    LifecycleRunWorker,
    LiveOwnerContext,
    build_lifecycle_worker,
)
from thymira.core.lifecycle_worker import (
    BoundedControlInputConsumer,
    ControlHandler,
    ControlInputConsumer,
    GoalBoardCommandConsumer,
    LifecycleOwnerLoop,
    TerminalAuditor,
    WorkExecutor,
)
from thymira.core.lineage import cascade_invalidation
from thymira.core.orchestrator_board import (
    BoardAuthorityError,
    BoardDependencyError,
    LifecycleWorkWriter,
    OrchestratorBoard,
    OrchestratorBoardError,
)
from thymira.core.phases import (
    PHASE_ORDER,
    REOPENABLE_PHASES,
    Phase,
    can_reopen,
    next_phase,
    phase_precedes,
)
from thymira.core.project_inputs import (
    ContextDocument,
    DatasetUpload,
    DatasetUploadResult,
    DeclaredDataset,
    ProjectInputConflictError,
    ProjectInputError,
    ProjectInputNotFoundError,
    ProjectInputs,
    ProjectInputTooLargeError,
)
from thymira.core.projects import ProjectResolution, ProjectResolver, load_project_config
from thymira.core.provenance import (
    DEFAULT_DISTRIBUTIONS,
    RunEnvironment,
    RuntimeInfo,
    SourceControl,
    capture_run_environment,
    distribution_versions,
    hash_inputs,
    source_control,
)
from thymira.core.queue import (
    QueueDispatcher,
    QueueTransportError,
    TaskConsumer,
    TaskPublisher,
    WorkNotificationDecodeError,
    notification_from_bytes,
    notification_to_bytes,
)
from thymira.core.rework import REWORK_TARGETS, ReworkTranslation, rework_signal_from_decision
from thymira.core.risk_interview import (
    PendingRiskQuestion,
    RiskInterviewError,
    RiskInterviewModelContext,
    RiskInterviewNotPendingError,
    RiskInterviewService,
    RiskInterviewStatus,
    SufficiencyJudgment,
)
from thymira.core.run_state import (
    InvalidRunStateError,
    InvalidRunTransitionError,
    RunCondition,
    RunOutcome,
    RunProjection,
    RunStage,
    RunState,
    RunStateError,
    RunTransitionCommand,
    RunTransitionEvent,
    RunTransitionKind,
    RunTransitionResult,
    StaleRunVersionError,
    WaitReason,
    allowed_transitions,
    apply_transition,
    initial_run_state,
)
from thymira.core.runs import (
    RunApprovalError,
    RunAuditStaleError,
    RunInformationRequiredError,
    RunNotAwaitingApprovalError,
    RunNotFoundError,
    RunNotResumableError,
    RunService,
)
from thymira.core.sessions import (
    SessionNotFoundError,
    SessionProjectMismatchError,
    SessionService,
)
from thymira.core.usage import UsageLedger, UsageLedgerRegistry
from thymira.core.worker import (
    build_production_lifecycle_worker,
    resolve_run_model_route_policy,
)

__all__ = [
    "DEFAULT_DISTRIBUTIONS",
    "PHASE_ORDER",
    "REOPENABLE_PHASES",
    "REWORK_TARGETS",
    "AnalyticalAnswer",
    "AuditFreshnessAssessment",
    "AuditFreshnessService",
    "AuthorizationError",
    "AuthorizationScopeError",
    "AutomaticResolver",
    "AutonomousRoundLimitError",
    "BoardAuthorityError",
    "BoardDependencyError",
    "BoundedControlInputConsumer",
    "ContextDocument",
    "ControlHandler",
    "ControlInputConsumer",
    "ControlPlaneResult",
    "DatasetUpload",
    "DatasetUploadResult",
    "DecisionMode",
    "DecisionRequest",
    "DecisionResolution",
    "DecisionResolver",
    "DeclaredDataset",
    "DuplicateExecutionError",
    "ExecutionDispatchError",
    "ExecutionDispatcher",
    "ExpiredAuthorizationError",
    "GoalAuthorityError",
    "GoalBoardCommandConsumer",
    "GoalBoardConfig",
    "GoalBoardError",
    "GoalBoardService",
    "GoalRevisionConflictError",
    "GraphFactory",
    "HumanConfirmResolver",
    "IdempotencyJournal",
    "InlineDispatcher",
    "InvalidRunStateError",
    "InvalidRunTransitionError",
    "LifecycleGraphExecutor",
    "LifecycleNotificationConsumer",
    "LifecycleOwnerLoop",
    "LifecycleRunWorker",
    "LifecycleWorkWriter",
    "LiveOwnerContext",
    "LlmProposesHumanConfirmsResolver",
    "MiraControlPlane",
    "MiraSubgraph",
    "OrchestratorBoard",
    "OrchestratorBoardError",
    "PendingRiskQuestion",
    "Phase",
    "PlanReviewRequiredError",
    "ProjectInputConflictError",
    "ProjectInputError",
    "ProjectInputNotFoundError",
    "ProjectInputTooLargeError",
    "ProjectInputs",
    "ProjectResolution",
    "ProjectResolver",
    "QueueDispatcher",
    "QueueTransportError",
    "RepeatBlockedError",
    "RepeatDecision",
    "ReusedAuthorizationError",
    "ReworkTranslation",
    "RiskInterviewError",
    "RiskInterviewModelContext",
    "RiskInterviewNotPendingError",
    "RiskInterviewService",
    "RiskInterviewStatus",
    "RunApprovalError",
    "RunAuditStaleError",
    "RunCondition",
    "RunController",
    "RunEnvironment",
    "RunEventLog",
    "RunGraphState",
    "RunInformationRequiredError",
    "RunNotAwaitingApprovalError",
    "RunNotFoundError",
    "RunNotResumableError",
    "RunOutcome",
    "RunProjection",
    "RunService",
    "RunStage",
    "RunState",
    "RunStateError",
    "RunTransitionCommand",
    "RunTransitionEvent",
    "RunTransitionKind",
    "RunTransitionResult",
    "RuntimeInfo",
    "RuntimeState",
    "SessionNotFoundError",
    "SessionProjectMismatchError",
    "SessionService",
    "SourceControl",
    "StaleRunVersionError",
    "StateCheckpointer",
    "Subgraph",
    "SubgraphDeps",
    "SufficiencyJudgment",
    "TaskConsumer",
    "TaskPublisher",
    "TerminalAuditor",
    "ThyExecutionError",
    "ThySubgraph",
    "UsageLedger",
    "UsageLedgerRegistry",
    "WaitReason",
    "WorkExecutor",
    "WorkNotificationDecodeError",
    "allowed_transitions",
    "apply_transition",
    "build_audit_agent_runner",
    "build_lifecycle_worker",
    "build_production_lifecycle_worker",
    "build_risk_interview_model_context",
    "build_runtime_graph",
    "build_runtime_graph_factory",
    "can_reopen",
    "capture_run_environment",
    "cascade_invalidation",
    "composed_graph_definition_hash",
    "compute_execution_key",
    "default_activity_profile",
    "default_thy_catalog",
    "deserialize_runtime_state",
    "distribution_versions",
    "graph_definition_hash",
    "hash_inputs",
    "initial_graph_state",
    "initial_run_state",
    "initial_runtime_state",
    "load_project_config",
    "next_phase",
    "notification_from_bytes",
    "notification_to_bytes",
    "phase_precedes",
    "resolve_run_model_route_policy",
    "rework_signal_from_decision",
    "serialize_runtime_state",
    "source_control",
    "write_run_assurance",
]
