"""A small sequential orchestrator for deterministic MIRA audit work."""

from __future__ import annotations

import hashlib
from datetime import datetime
from typing import TYPE_CHECKING

from pydantic import model_validator

from thymira.events import canonical_json
from thymira.mira.checks import (
    AuditContext,
    AuditMode,
    AuditReport,
    ControlResult,
    ControlStatus,
    audit_run,
)
from thymira.mira.checks.controls import _stable_finding_id
from thymira.mira.evidence import artifact_manifest_sha256
from thymira.mira.finding_safety import safe_finding
from thymira.mira.preflight import (
    ApplicabilityResolver,
    BaseRiskEvaluator,
    EvidenceObservation,
    GenericPackControlRunner,
    ReviewedPack,
    RiskAssessmentModelContext,
)
from thymira.mira.verification import _prefer_finding, finding_dedup_key
from thymira.schemas import (
    ActionIntent,
    ActionKind,
    ActivityProfile,
    Actor,
    AuditFinding,
    ControlEvaluation,
    ControlEvaluationStatus,
    DagBoard,
    Event,
    EventType,
    Framework,
    PackBinding,
    PlanBoard,
    RiskAssessment,
    Run,
    Severity,
    ThymiraModel,
)

if TYPE_CHECKING:
    from collections.abc import Sequence

    from thymira.state import ArtifactStore


class MiraAuditSnapshot(ThymiraModel):
    """Immutable Run evidence supplied to the sequential MIRA audit flow.

    ``frameworks`` names the governance frameworks this Run is audited against. It is what the
    requirements-coverage control (A26) resolves the requirements->controls mapping through:
    left empty, A26 has no declared framework and asserts nothing. Core supplies this value from
    the project's governance declaration.
    """

    run: Run
    activity_profile: ActivityProfile
    events: tuple[Event, ...] = ()
    evidence_observations: tuple[EvidenceObservation, ...] = ()
    frameworks: tuple[Framework, ...] = ()
    audit_mode: AuditMode = AuditMode.FINAL
    audited_at: datetime
    plan_history: tuple[PlanBoard, ...] = ()
    dag_board: DagBoard | None = None
    block_after_same_cause: int = 3

    @model_validator(mode="after")
    def validate_profile_owner(self) -> MiraAuditSnapshot:
        """Require the activity profile to describe the Run supplied to MIRA."""
        if self.activity_profile.run_id != self.run.id:
            raise ValueError("activity_profile.run_id must match snapshot.run.id")
        return self


class MiraAuditResult(ThymiraModel):
    """The complete evidence and proposals generated by one MIRA audit invocation."""

    risk_assessment: RiskAssessment
    pack_bindings: tuple[PackBinding, ...]
    control_evaluations: tuple[ControlEvaluation, ...]
    audit_findings: tuple[AuditFinding, ...]
    audit_report: AuditReport
    action_intents: tuple[ActionIntent, ...]


class MiraPreflightResult(ThymiraModel):
    """The inherent-risk and applicability evidence available before THY execution."""

    risk_assessment: RiskAssessment
    pack_bindings: tuple[PackBinding, ...]
    audit_findings: tuple[AuditFinding, ...]


class MiraEvidenceAuditResult(ThymiraModel):
    """Evidence-control results that require the evidence THY has produced."""

    control_evaluations: tuple[ControlEvaluation, ...]
    control_results: tuple[ControlResult, ...]
    audit_findings: tuple[AuditFinding, ...]


class MiraAuditOrchestrator:
    """Run the bounded MIRA audit sequence without authorizing or persisting any effect."""

    def __init__(
        self,
        packs: Sequence[ReviewedPack],
        actor: Actor,
        *,
        risk_model_context: RiskAssessmentModelContext | None = None,
    ) -> None:
        self._packs = _unique_packs(packs)
        self._actor = actor
        self._risk_model_context = risk_model_context

    def audit(
        self, snapshot: MiraAuditSnapshot, *, store: ArtifactStore | None = None
    ) -> MiraAuditResult:
        """Evaluate risk, packs, controls, integrity checks, findings, and review intents."""
        preflight = self.run_governance_preflight(snapshot)
        evidence_audit = self.run_evidence_audit(snapshot, preflight)
        deterministic_report = self.run_deterministic(snapshot, store=store)
        findings = _deduplicate_findings(
            (
                *preflight.audit_findings,
                *evidence_audit.audit_findings,
                *deterministic_report.findings,
            )
        )
        return self.assemble_result(
            snapshot,
            preflight,
            evidence_audit,
            deterministic_report,
            findings,
        )

    def run_governance_preflight(self, snapshot: MiraAuditSnapshot) -> MiraPreflightResult:
        """Evaluate inherent risk and pack applicability before THY produces evidence."""
        risk_method = next((pack.risk_method for pack in self._packs if pack.risk_method), None)
        if risk_method is None:
            raise ValueError("MIRA audit requires one reviewed base-risk method")

        profile = snapshot.activity_profile
        risk_assessment = BaseRiskEvaluator(
            risk_method,
            self._actor,
            model_context=self._risk_model_context,
        ).evaluate(
            profile,
            assessment_id=_stable_id(
                "assessment",
                {"profile": profile.id, "at": snapshot.audited_at},
            ),
            assessed_at=snapshot.audited_at,
        )

        resolver = ApplicabilityResolver()
        bindings = tuple(
            resolver.resolve(
                profile,
                pack,
                binding_id=_stable_id(
                    "binding",
                    {"profile": profile.id, "pack": pack.id, "at": snapshot.audited_at},
                ),
                evaluated_as_of=snapshot.audited_at,
            )
            for pack in self._packs
        )

        findings = _risk_findings(risk_assessment, snapshot.run.id, snapshot.audited_at)
        return MiraPreflightResult(
            risk_assessment=risk_assessment,
            pack_bindings=bindings,
            audit_findings=findings,
        )

    def run_evidence_audit(
        self, snapshot: MiraAuditSnapshot, preflight: MiraPreflightResult
    ) -> MiraEvidenceAuditResult:
        """Evaluate applicable pack controls against the evidence available after THY."""
        runner = GenericPackControlRunner()
        packs_by_id = {pack.id: pack for pack in self._packs}
        evaluations: list[ControlEvaluation] = []
        for binding in preflight.pack_bindings:
            pack = packs_by_id.get(binding.pack_id)
            if pack is None:
                raise ValueError(f"MIRA preflight binding names unknown pack {binding.pack_id!r}")
            if not binding.applicable:
                continue
            evaluations.extend(
                runner.evaluate(
                    binding,
                    pack,
                    control,
                    snapshot.evidence_observations,
                    evaluation_id=_stable_id(
                        "control",
                        {
                            "binding": binding.id,
                            "control": control.id,
                            "at": snapshot.audited_at,
                        },
                    ),
                    evaluated_at=snapshot.audited_at,
                )
                for control in pack.controls
            )
        evaluation_tuple = tuple(evaluations)
        control_results = tuple(_control_result(evaluation) for evaluation in evaluations)
        findings = _deduplicate_findings(
            (
                *(
                    _evaluation_finding(evaluation, snapshot.run.id, snapshot.audited_at)
                    for evaluation in evaluation_tuple
                ),
            )
        )
        return MiraEvidenceAuditResult(
            control_evaluations=evaluation_tuple,
            control_results=control_results,
            audit_findings=findings,
        )

    def run_deterministic(
        self, snapshot: MiraAuditSnapshot, *, store: ArtifactStore | None = None
    ) -> AuditReport:
        """Run the existing deterministic controls against the immutable input snapshot."""
        report = audit_run(
            AuditContext(
                snapshot.run.id,
                snapshot.events,
                store,
                policy_sha256=_expected_policy_sha256(snapshot.events),
                frameworks=snapshot.frameworks,
                audit_mode=snapshot.audit_mode,
                audited_at=snapshot.audited_at,
            )
        )
        findings = _deduplicate_findings(
            tuple(
                _check_finding(result, snapshot.run.id, snapshot.audited_at)
                for result in report.controls
            )
        )
        return report.model_copy(
            update={
                "findings": findings,
                "manifest_sha256": artifact_manifest_sha256(store),
                "activity_profile_id": snapshot.activity_profile.id,
                "activity_profile_version": snapshot.activity_profile.version,
            }
        )

    def assemble_result(
        self,
        snapshot: MiraAuditSnapshot,
        preflight: MiraPreflightResult,
        evidence_audit: MiraEvidenceAuditResult,
        deterministic_report: AuditReport,
        findings: tuple[AuditFinding, ...],
    ) -> MiraAuditResult:
        """Assemble one audit result from already evaluated and deduplicated evidence."""
        findings = _deduplicate_findings(findings)
        control_results = (*deterministic_report.controls, *evidence_audit.control_results)
        report = _audit_report(snapshot.run.id, deterministic_report, control_results, findings)
        intents = tuple(
            _review_intent(finding, snapshot.run.id, self._actor, snapshot.audited_at)
            for finding in findings
        )
        return MiraAuditResult(
            risk_assessment=preflight.risk_assessment,
            pack_bindings=preflight.pack_bindings,
            control_evaluations=evidence_audit.control_evaluations,
            audit_findings=findings,
            audit_report=report,
            action_intents=intents,
        )


def _unique_packs(packs: Sequence[ReviewedPack]) -> tuple[ReviewedPack, ...]:
    """Keep the first reviewed definition for each pack id in caller order."""
    unique: dict[str, ReviewedPack] = {}
    for pack in packs:
        unique.setdefault(pack.id, pack)
    return tuple(unique.values())


def _stable_id(kind: str, facts: dict[str, object]) -> str:
    """Return a reproducible prefixed identifier from canonical facts."""
    serializable = {
        key: value.isoformat() if isinstance(value, datetime) else value
        for key, value in facts.items()
    }
    digest = hashlib.sha256(canonical_json(serializable).encode("utf-8")).hexdigest()[:32]
    return f"{kind}_{digest}"


def _control_result(evaluation: ControlEvaluation) -> ControlResult:
    """Represent a preflight control evaluation in the aggregate audit report."""
    status = (
        ControlStatus.PASSED
        if evaluation.status is ControlEvaluationStatus.SATISFIED
        else ControlStatus.NOT_EVALUATED
        if evaluation.status is ControlEvaluationStatus.REQUIRES_HUMAN_REVIEW
        else ControlStatus.FAILED
    )
    severity = (
        Severity.HIGH if evaluation.status is ControlEvaluationStatus.FAILED else Severity.MEDIUM
    )
    return ControlResult(
        control_id=evaluation.control_id,
        title=f"Preflight control {evaluation.control_id}",
        status=status,
        severity=severity,
        detail=evaluation.status.value,
        evidence=evaluation.evidence,
    )


def _risk_findings(
    assessment: RiskAssessment, run_id: str, audited_at: datetime
) -> tuple[AuditFinding, ...]:
    """Return the one proposal required when base-risk facts are missing."""
    if not assessment.missing_information:
        return ()
    finding = "Missing profile facts: " + ", ".join(assessment.missing_information)
    return (
        safe_finding(
            AuditFinding(
                id=_stable_id(
                    "finding", {"run": run_id, "control": "MIRA-RISK-001", "at": audited_at}
                ),
                run_id=run_id,
                control_id="MIRA-RISK-001",
                framework=Framework.METHODOLOGY,
                title="Base risk cannot be classified",
                finding=finding,
                severity=Severity.MEDIUM,
                confidence=1.0,
                evidence=assessment.evidence,
                recommendation=(
                    "Provide the missing profile facts and repeat the deterministic review."
                ),
                created_at=audited_at,
            )
        ),
    )


def _evaluation_finding(
    evaluation: ControlEvaluation, run_id: str, audited_at: datetime
) -> AuditFinding | None:
    """Turn a non-satisfied preflight control into a MIRA finding, never a decision."""
    if evaluation.status is ControlEvaluationStatus.SATISFIED:
        return None
    severity = (
        Severity.HIGH if evaluation.status is ControlEvaluationStatus.FAILED else Severity.MEDIUM
    )
    return safe_finding(
        AuditFinding(
            id=_stable_id(
                "finding",
                {
                    "run": run_id,
                    "pack": evaluation.pack_id,
                    "binding": evaluation.pack_binding_id,
                    "control": evaluation.control_id,
                    "at": audited_at,
                },
            ),
            run_id=run_id,
            control_id=evaluation.control_id,
            framework=Framework.METHODOLOGY,
            title=f"Preflight control {evaluation.control_id} needs attention",
            finding=f"Evidence status: {evaluation.status.value}.",
            severity=severity,
            confidence=1.0,
            evidence=evaluation.evidence,
            recommendation="Review the evidence and repeat the control evaluation.",
            created_at=audited_at,
        )
    )


def _check_finding(result: ControlResult, run_id: str, audited_at: datetime) -> AuditFinding | None:
    """Turn a failed deterministic integrity check into a deterministic finding."""
    if result.status is not ControlStatus.FAILED:
        return None
    return safe_finding(
        AuditFinding(
            id=_stable_finding_id(run_id, result.control_id, audited_at),
            run_id=run_id,
            control_id=result.control_id,
            framework=Framework.INTERNAL,
            title=result.title,
            finding=result.detail or "deterministic control failed",
            severity=result.severity,
            confidence=1.0,
            evidence=result.evidence,
            recommendation="Inspect the referenced evidence and repeat the deterministic audit.",
            created_at=audited_at,
        )
    )


def _expected_policy_sha256(events: Sequence[Event]) -> str | None:
    """Return the policy snapshot recorded when the Run started, if present."""
    for event in events:
        if event.type is EventType.RUN_STARTED:
            value = event.payload.get("policy_sha256")
            return value if isinstance(value, str) else None
    return None


def _deduplicate_findings(findings: Sequence[AuditFinding | None]) -> tuple[AuditFinding, ...]:
    """Keep the most severe finding per key in stable input order."""
    unique: dict[tuple[str, str, tuple[str, ...]], AuditFinding] = {}
    for finding in findings:
        if finding is not None:
            safe = safe_finding(finding)
            key = finding_dedup_key(safe)
            unique[key] = _prefer_finding(unique[key], safe) if key in unique else safe
    return tuple(unique.values())


def _audit_report(
    run_id: str,
    deterministic_report: AuditReport,
    controls: Sequence[ControlResult],
    findings: tuple[AuditFinding, ...],
) -> AuditReport:
    """Build the one aggregate report without trusting random identifiers from a sub-report."""
    failed = [control for control in controls if control.status is ControlStatus.FAILED]
    if any(control.severity in (Severity.HIGH, Severity.CRITICAL) for control in failed):
        status = "failed"
    elif failed or findings:
        status = "passed_with_warnings"
    else:
        status = "passed"
    summary = {
        item.value: sum(1 for control in controls if control.status is item)
        for item in ControlStatus
    }
    return deterministic_report.model_copy(
        update={
            "run_id": run_id,
            "control_set": "thymira-mira-audit@0.1",
            "status": status,
            "controls": tuple(controls),
            "findings": findings,
            "summary": summary,
        }
    )


def _review_intent(
    finding: AuditFinding, run_id: str, actor: Actor, audited_at: datetime
) -> ActionIntent:
    """Request a bounded review of one finding without granting any authority."""
    intent_id = _stable_id("intent", {"finding": finding.id, "at": audited_at})
    return ActionIntent(
        id=intent_id,
        run_id=run_id,
        requester=actor,
        action_kind=ActionKind.REVIEW_FINDINGS,
        subject_kind="findings",
        subject_id=finding.id,
        purpose=f"Review MIRA finding {finding.control_id}.",
        payload={"control_id": finding.control_id, "finding_id": finding.id},
        evidence=finding.evidence,
        idempotency_key=f"mira-review-{intent_id}",
        created_at=audited_at,
    )
